name: build-hermesc-apple

on: workflow_call

jobs:
  build-hermesc-apple:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup xcode
        uses: ./.github/actions/setup-xcode
      - name: Build HermesC Apple
        shell: bash
        run: |
          source ./utils/build-apple-framework.sh
          build_host_hermesc_if_needed
      - name: Upload HermesC Artifact
        uses: actions/upload-artifact@v6
        with:
          name: hermesc-apple
          path: ./build_host_hermesc
