name: Publish Tag
on:
  workflow_dispatch:
    inputs:
      release-type:
        required: true
        description: The type of release we are building. It could be commitly, release or dry-run
        type: choice
        options:
          - release
          - commitly
          - dry-run
      hermes-version:
        required: true
        description: The Hermes version to use for this tag. It will be used to create the tag name of the form hermes-v${ hermes-version }
        type: string
  workflow_call:
    inputs:
      release-type:
        required: true
        description: The type of release we are building. It could be commitly, release or dry-run
        type: string
      hermes-version:
        required: true
        description: The Hermes version to use for this tag. It will be used to create the tag name of the form hermes-v${ hermes-version }
        type: string

jobs:
  publish:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Print the target SHA and hermes version
        run: |
          echo "targetSha=${{ github.sha }}"
          echo "hermes-version=${{ inputs.hermes-version }}"
      - name: Create tag
        if: ${{ inputs.release-type == 'release' }}
        uses: actions/github-script@v8
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/hermes-v${{ inputs.hermes-version }}',
              sha: '${{ github.sha }}',
            })
