[package]
name = "juno"
version = "0.1.0"
authors = ["Facebook"]
edition = "2018"
license = "MIT"

[dependencies]
hermes = { path = "../hermes" }
support = { path = "../support" }
libc = "0.2"
thiserror = "1.0"
sourcemap = "6.0"
memoffset = "0.6.1"
paste = "1.0"

[dev-dependencies]
assert_cmd = "0.12"
toml = "=0.5.7"
