[package]
name = "juno"
version = "0.1.0"
authors = ["Facebook"]
edition = "2018"
license = "MIT"

[[bin]]
name = "juno"
path = "src/bin/main.rs"

[dependencies]
hermes = { path = "../hermes" }
support = { path = "../support" }
libc = "0.2"
structopt = "0.3"
thiserror = "1.0"
anyhow = "1.0"
url = "2.2.2"
sourcemap = "6.0"

[dev-dependencies]
assert_cmd = "0.12"
